### ISSUE TITLE
v1beta1 support

### ISSUE THREAD

**Issue by lynnsh** [grafeas/client-go#14]
Hi! I am currently working on adding Grafeas support in [Voucher](https://github.com/Shopify/voucher), and the current version of the client (v1alpha1) does not work with the docker grafeas image.

Are there any plans to make v1beta1 version available as specified in https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/grafeas.proto?

**Comment by aysylu** [comment]
Hi @lynnsh, thanks for your question! We moved to semantic versioning for the client libraries, so the new one is `0.1.0`. Apologies for the confusion!

**Comment by lynnsh** [comment]
Thank you for the clarification!
